[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "parsed-vhdl-domain"
description = "Sphinx domain for VHDL"
version = "0.1.0"
authors = [
    { name = "JF Cliche", email = "vhdl@jfcliche.com" }
]
dependencies = [
    "vsg @ git+https://github.com/jfcliche/vhdl-style-guide.git@48a0b70"
]

[tool.setuptools.package-data]
parsed_vhdl_domain = ["*.css", ".nojekyll"]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
    "sphinxcontrib.restbuilder"  # used for debugging output
]



